name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'

env:
  LLVM_VERSION: 12.0.0
  LLVM_VERSION_MAJOR: 12

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Install LLVM on macOS
        run: |
          brew install llvm@${{ env.LLVM_VERSION_MAJOR }}
          cd /usr/local/opt/
          ls -l
          cd /usr/local/Cellar/
          ls -l
