name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'

env:
  LLVM_VERSION: 13.0.0
  LLVM_VERSION_MAJOR: 13

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Install LLVM on macOS
        run: |
          brew install llvm@${{ env.LLVM_VERSION_MAJOR }}
          ls -l /usr/local/opt/llvm*
          ls -l /usr/local/Cellar/llvm*
